
service: aws-node-auth0-cognito

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  deploymentBucket: deploy-serverless-americatv

functions:
  publicEndpoint:
    handler: handler.publicEndpoint
    events:
      - http:
          path: api/public
          method: get
          integration: lambda
          cors: true
  login:
    handler: handler.publicEndpointLogin
    events:
      - http:
          path: api/login
          method: get
          integration: lambda
          cors: true
          request:
            parameters:
              querystrings:
                user: true
                password: true
  auth:
    handler: auth.authorize
  privateEndpoint:
    handler: handler.privateEndpoint
    events:
      - http:
          path: api/private
          method: get
          authorizer: auth
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
