
service: aws-node-auth0-cognito

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  deploymentBucket: egp-deploy
  tracing:
    apiGateway: true
  logs:
    restApi: true
plugins:
  - serverless-plugin-split-stacks
custom:
  splitStacks:
    perFunction: true
    perType: false
    perGroupFunction: false
    stackConcurrency: 5 # Controls if enabled and how much stacks are deployed in parallel. Disabled if absent.
    resourceConcurrency: 10 # Controls how much resources are deployed in parallel. Disabled if absent.

functions:
  publicEndpoint:
    handler: handler.publicEndpoint
    events:
      - http:
          path: api/public
          method: get
          integration: lambda
          cors: true
  login:
    handler: handler.login
    events:
      - http:
          path: api/login
          method: get
          integration: lambda
          cors: true
          request:
            parameters:
              querystrings:
                user: true
                password: true
  register:
    handler: handler.RegisterUser
    events:
      - http:
          path: api/register-user
          method: post
          integration: lambda
          cors: true
          request:
            parameters:
              querystrings:
                user: true
                password: true
  auth:
    handler: auth.authorize
  privateEndpoint:
    handler: handler.privateEndpoint
    events:
      - http:
          path: api/private
          method: get
          authorizer: auth
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
